--ACESSOS------------------


SELECT DISTINCT

   GR__RL_ID AS PRIVILEGIO_ID,
   GR__RL_CODIGO AS PRIVILEGIO_NOME,  
   GROUP_ID AS GRUPO_ID,
   GR__CODIGO AS GRUPO_NOME,
   U.USR_ID,
    USR_CODIGO AS USUARIO,
   USR_NOME AS NOME
  ,RL__ROTINA AS ROTINA,
   RL__ITEM AS ITEM,
 RL__DESMDEF AS OPCAO
       
  FROM TMPROD.Sys_Rules_Grp_Rules R
  LEFT JOIN TMPROD.Sys_Grp_GROUP G ON  R.GROUP_ID = G.GR__ID
  LEFT JOIN TMPROD.SYS_USR_GROUPS UG ON G.GR__ID = UG.USR_GRUPO
  LEFT JOIN TMPROD.SYS_USR U ON UG.USR_ID = U.USR_ID
 LEFT JOIN TMPROD.Sys_Rules_Features F ON R.GR__RL_ID = F.RL__ID

WHERE --R.GR__RL_ID = '000929'
      --G.GR__ID = '000474 '
      -- R.GR__RL_CODIGO LIKE '%FECH%'
      U.USR_CODIGO = '' AND
      --U.USR_NOME = 'Luiz Henrique dos Santos Salmaso'
     F.RL__ROTINA = 'FINA130'

ORDER BY GR__RL_ID ,GROUP_ID,U.USR_ID,RL__ROTINA;

--U.USR_CODIGO,RL__ITEM







--SELECT * FROM TMPROD.Sys_Grp_Module M WHERE M.GR__MODULO = '5' AND M.GR__ACESSO = 'T'


