SELECT 
      
       C5_NOTA,
       C5_NUM,
        d2_total,
       C5_XVALFRE,
       C5_XAICFRE,
       C5_XICMFRE,
       DAK_COD,
       DAK_PESO,
       DAI_PESO
  FROM TMPROD.SF2010 SF2

   
  
  LEFT JOIN TMPROD.DAI010 DAI
  ON SF2.F2_FILIAL = DAI.DAI_FILIAL
  AND SF2.F2_CARGA = DAI.DAI_COD
  AND DAI.D_E_L_E_T_ =  ' ' 
  
  LEFT JOIN TMPROD.DAK010 DAK
  ON SF2.F2_FILIAL = DAK.DAK_FILIAL
  AND SF2.F2_CARGA = DAK.DAK_COD
  AND DAK.D_E_L_E_T_ =  ' ' 
  
  LEFT JOIN TMPROD.SC5010 SC5
  ON DAI.DAI_FILIAL = SC5.C5_FILIAL
  AND DAI.DAI_PEDIDO = SC5.C5_NUM
  AND SC5.D_E_L_E_T_ =  ' ' 
  
  LEFT JOIN TMPROD.SD2010 SD2
  ON SC5.C5_FILIAL = SD2.D2_FILIAL
  AND SC5.C5_NUM = SD2.D2_PEDIDO
  AND SD2.D_E_L_E_T_ =  ' ' 
  
 WHERE SF2.F2_DOC = '000057697'
   AND SF2.F2_FILIAL = '01001';
   
   
 -------------------------------------------------------  
   
   
 SELECT 
      
       C5_NOTA,
       C5_NUM,
       F2_VALMERC,
       C5_XVALFRE,
       C5_XAICFRE,
       C5_XICMFRE,
       DAK_COD,
       DAK_PESO,
       DAI_PESO
       
  FROM TMPROD.DAK010 DAK  
  
  LEFT JOIN TMPROD.DAI010 DAI
  ON DAK.DAK_FILIAL = DAI.DAI_FILIAL
  AND DAK.DAK_COD = DAI.DAI_COD
  AND DAI.D_E_L_E_T_ =  ' ' 
  
  LEFT JOIN TMPROD.SC5010 SC5
  ON DAI.DAI_FILIAL = SC5.C5_FILIAL
  AND DAI.DAI_PEDIDO = SC5.C5_NUM
  AND SC5.D_E_L_E_T_ =  ' ' 
  
  LEFT JOIN TMPROD.SF2010 SF2
  ON SC5.C5_FILIAL = SF2.F2_FILIAL
  AND SC5.C5_NOTA = SF2.F2_DOC
  AND SF2.D_E_L_E_T_ =  ' ' 
  
 WHERE DAK.DAK_COD = '094006'
   AND DAK.DAK_FILIAL = '01001';

