SELECT SC5.C5_NUM,
       SF3.F3_FILIAL,
       SF3.F3_EMISSAO,
       SF3.F3_NFISCAL,
       SF3.F3_SERIE,
       F2_TRANSP,
       SA1.A1_CGC,
       SA1.A1_NREDUZ,
       SA1.A1_EST,
       SF2.F2_TPFRETE,
       SA4.A4_CGC,
       SA4.A4_NREDUZ,
       SA4.A4_EST,
       D2_TOTAL,
       D2_VALFRE,
       D2_ICMFRET,
       SC5.C5_XVALFRE,
       SC5.C5_XAICFRE,
       SC5.C5_XICMFRE
  FROM TMPROD.SF3010 SF3
 INNER JOIN TMPROD.SF2010 SF2
    ON F2_FILIAL = SF3.F3_FILIAL
   AND SF2.F2_DOC = SF3.F3_NFISCAL
   AND SF2.F2_SERIE = SF3.F3_SERIE
   AND SF2.F2_CLIENTE = SF3.F3_CLIEFOR
   AND SF2.F2_LOJA = SF3.F3_LOJA
   AND SF2.D_E_L_E_T_ = ' '

 INNER JOIN TMPROD.SD2010 SD2
    ON D2_FILIAL = SF3.F3_FILIAL
   AND SD2.D2_DOC = SF3.F3_NFISCAL
   AND SD2.D2_SERIE = SF3.F3_SERIE
   AND SD2.D2_CLIENTE = SF3.F3_CLIEFOR
   AND SD2.D2_LOJA = SF3.F3_LOJA
   AND SD2.D_E_L_E_T_ = ' '

 INNER JOIN TMPROD.SA4010 SA4
-- ON    SA4.A4_FILIAL = SF2.F2_FILIAL AND
    ON SA4.A4_COD = SF2.F2_TRANSP
   AND SA4.D_E_L_E_T_ = ' '

 INNER JOIN TMPROD.SA1010 SA1
--  SA1.A1_FILIAL = SF3.F3_FILIAL AND
    ON SA1.A1_COD = SF3.F3_CLIEFOR
   AND SA1.A1_LOJA = SF3.F3_LOJA
   AND SA1.D_E_L_E_T_ = ' '

 INNER JOIN TMPROD.SC9010 SC9
    ON SC9.C9_FILIAL = SF2.F2_FILIAL
   AND C9_NFISCAL = F2_DOC
   AND C9_SERIENF = F2_SERIE
   AND C9_CLIENTE = F2_CLIENTE
   AND C9_LOJA = F2_LOJA
   AND SC9.D_E_L_E_T_ = ' '

 INNER JOIN TMPROD.SC5010 SC5
    ON SC5.C5_FILIAL = SC9.C9_FILIAL
   AND C5_NUM = C9_PEDIDO
   AND C5_XICMFRE > 0
   AND C5_XVALFRE > 0
   AND SC5.D_E_L_E_T_ = ' '

 WHERE SF3.F3_FILIAL = '01001'
      
   AND SC5.
