SELECT TJ_FILIAL AS "FILIAL",
       TJ_ORDEM AS "ORDEM_SERVICO",
       TO_CHAR(TO_DATE(TRIM(TJ_DTORIGI), 'YYYYMMDD'), 'DD/MM/YYYY') AS "DT_ORIGINAL",
       UPPER(DECODE(TJ_TIPOOS,
                    'B',
                    'BEM',
                    'L',
                    'LOCALIZAÇÃO' ))
                     AS "TIPO_OS",
       TJ_CODBEM AS "BEM",
       --TJ_NOMBEM AS "NOME_BEM",
       TJ_SERVICO AS "SERVICO",
       T4_NOME AS "NOME_SERVICO", 
       TJ_TIPO AS "TIPO_MANUTENCAO",
       TE_NOME AS "NOME_TIPO_M",
       TJ_CODAREA AS "AREA_MANUTENCAO",
       TD_NOME AS "NOME_AREA",            
       TJ_CCUSTO AS "C_CUSTO",
       CTT_DESC01 AS "DESCRICAO",
       TJ_USUARIO AS "USUARIO_ALT",
       DECODE (TJ_TERCEIR,
                     '1',
                     'NÃO',
                     '2',
                     'SIM')AS "TERCEIRO",
       UPPER(DECODE(TJ_SITUACA, 
       'C','CANCELADO','L','LIBERADO','P','PENDENTE' ))
                        AS "SITUACAO", 
       TO_CHAR(TO_DATE(TRIM(T9_DTBAIXA), 'YYYYMMDD'), 'DD/MM/YYYY') AS "DT_BAIXA",
       T9_CODIMOB AS "IMOBILIZADO",
       T9_NOME AS "NOME_BEM",
       T9_CHAPA AS "CHAMPA_IMOB",
       T9_PLACA AS "PLACA",
       T9_ANOMOD AS "ANO_MODELO",
       T9_ANOFAB AS "ANO_FABRIC",
       T9_CHASSI AS "CHASSI",
       T9_RENAVAM AS "RENAVAM",
       T9_NRMOTOR AS "NR_MOTOR",
       T9_NFCOMPR AS "NF_COMPRA",
       UPPER(DECODE(T9_SITBEM, 
       'A','Ativo','I','Inativo','T','Transferido' ))
                        AS "SITUACAO_BEM",
       T9_FORNECE AS "FORNECEDOR",
       T9_LOJA AS "LOJA", 
       A2_NOME AS "NOME_FORNECEDOR",
       TO_CHAR(TO_DATE(TRIM(T9_DTCOMPR), 'YYYYMMDD'), 'DD/MM/YYYY') AS "DT_COMPRA",
       T9_PRGARAN AS "PRAZO_GARANTIA",
       T9_UNGARAN AS "UNID_GARANTIA",
       TO_CHAR(TO_DATE(TRIM(T9_DTGARAN), 'YYYYMMDD'), 'DD/MM/YYYY') AS "DT_GARANTIA",
       T9_VALCPA AS "VALOR_COMPRA",
       TO_CHAR(TO_DATE(TRIM(T9_DTINSTA), 'YYYYMMDD'), 'DD/MM/YYYY') AS "DT_INSTALACAO",
       T9_CONTGAR AS "CONT_GARANTIA",
       T9_NFCOMPR AS "NF_COMPRA",
       T9_VALVENA AS "VLR_VENAL"       
       
 FROM TMPROD.STJ010 TJ
 INNER JOIN TMPROD.ST9010
 ON TJ_CODBEM = T9_CODBEM
 INNER JOIN TMPROD.ST4010
 ON TJ_SERVICO = T4_SERVICO
 INNER JOIN TMPROD.STE010
 ON TJ_TIPO = TE_TIPOMAN
 INNER JOIN TMPROD.STD010
 ON TJ_CODAREA = TD_CODAREA
 INNER JOIN TMPROD.CTT010
 ON TJ_CCUSTO = CTT_CUSTO
 LEFT JOIN TMPROD.SA2010
 ON T9_FORNECE = A2_COD
 
 WHERE TJ.D_E_L_E_T_ = ' '
 
 ORDER BY TJ_FILIAL, TJ_ORDEM
